name: Update README

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install figlet
        run: sudo apt-get update && sudo apt-get install -y figlet

      - name: Make script executable
        run: chmod +x generate-readme.sh

      - name: Run generate-readme.sh
        run: ./generate-readme.sh

      - name: Commit and push README.md if changed
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "comaff15"
          git config user.email "zavarykingleb@gmail.com"

          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "auto: update profile with ASCII motto [$(date +'%Y-%m-%d')]"
            git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }} HEAD:main
          fi
