name: Update README

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch: 

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install figlet
        run: sudo apt-get update && sudo apt-get install -y figlet

      - name: Make script executable
        run: chmod +x generate-readme.sh

      - name: Run generate-readme.sh
        run: ./generate-readme.sh

      - name: Commit and push README.md if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "auto: update profile with ASCII motto [$(date +'%Y-%m-%d')]"
            git push
          fi
